export const mockDataBank = [
  {
    id: 1,
    image: `/img/bank/kbank.png`,
    name: `ธ.กสิกรไทย`,
    number: `431-3-5533-6`,
    detail: `บจก. แอลเอ็นดับเบิ้ล`,
    type: `ออมทรัพย์`,
    branch: `สำนักงานสีลม`,
  },
  {
    id: 2,
    image: `/img/bank/scb.png`,
    name: `ธ.ไทยพาณิชย์`,
    number: `431-3-5533-6`,
    detail: `บจก. แอลเอ็นดับเบิ้ล`,
    type: `ออมทรัพย์`,
    branch: `สำนักงานสีลม`,
  },
  {
    id: 3,
    image: `/img/bank/bbl.png`,
    name: `ธ.กรุงเทพ`,
    number: `431-3-5533-6`,
    detail: `บจก. แอลเอ็นดับเบิ้ล`,
    type: `ออมทรัพย์`,
    branch: `สำนักงานสีลม`,
  },
  {
    id: 4,
    image: `/img/bank/ktb.png`,
    name: `ธ.กรุงไทย`,
    number: `431-3-5533-6`,
    detail: `บจก. แอลเอ็นดับเบิ้ล`,
    type: `ออมทรัพย์`,
    branch: `สำนักงานสีลม`,
  },
]